apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibm-automation
  template:
    metadata:
      labels:
        app: ibm-automation
    spec:
      containers:
      - name: ibm-automation
        image: cutthecheck/enterprise_automation:ibm
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ibm-service
spec:
  selector:
    app: ibm-automation
  ports:
    - port: 80
      targetPort: 8080
